### ISSUE TITLE
P569 & P570

### ISSUE THREAD

**Issue by SimonVilleneuvewp** [magnusmanske/auth2wd#1]
Hi,

Almost everytime I use the tool, I must correct P569 and/or P570 because the tool add a date less precise than the one already existing.

Is it possible that, when there's already a (unwiki or not) sourced value more precise than the ones added by the tool, it put the more precise value in best rank with the qualifiers P7452 -> Q71536040 ? (example : https://www.wikidata.org/wiki/Q28870540#P569 ) ?

Probably a more easy way : put the new less precise value in obsolete rank with qualifier P2241 -> Q42727519 (example : https://www.wikidata.org/wiki/Q608672#P569 )

**Comment by SimonVilleneuvewp** [comment]
ping ?

**Comment by SimonVilleneuvewp** [comment]
thank you for the work, but it seems it didn't works : https://www.wikidata.org/w/index.php?title=Q36584713&diff=prev&oldid=2118346474&diffmode=source

**Comment by SimonVilleneuvewp** [comment]
Issue tracking:

Less precise dates are indeed being deprecated, but without the Q42727519 qualifier.

Here is a small bug: The same date of death has been added to the item, with the same reference: https://www.wikidata.org/w/index.php?title=Q3438608&diff=prev&oldid=2125342765&diffmode=source

Is it relevant that I continue to report bugs here?

**Comment by magnusmanske** [comment]
Trying to untagle the various bugs in this thread:

> Less precise dates are indeed being deprecated, but without the Q42727519 qualifier.

Fixed.

> Here is a small bug: The same date of death has been added to the item, with the same reference: https://www.wikidata.org/w/index.php?title=Q3438608&diff=prev&oldid=2125342765&diffmode=source

This seems to be fixed, at least it doesn't try to add the date again:
https://ac2wd.toolforge.org/extend/Q3438608

> Another problem : The same date of birth or death is added when the qualifier Q26961029 is in the first value : https://www.wikidata.org/w/index.php?title=Q841173&diff=prev&oldid=2134268407&diffmode=source

This seems to be fixed:
https://ac2wd.toolforge.org/extend/Q841173

> Same when the date have a prefered rank : https://www.wikidata.org/w/index.php?title=Q102312327&diff=prev&oldid=2134817465&diffmode=source

This seems to be fixed as well:
https://ac2wd.toolforge.org/extend/Q102312327

I'm closing this, if there are still issues please re-open this issue if it's already mentioned here, op open a new issue.
