### ISSUE TITLE
GND redirects

### ISSUE THREAD

**Issue by SimonVilleneuvewp** [magnusmanske/auth2wd#5]
Hi again,

There's been [a discussion](https://www.wikidata.org/wiki/Topic:Xwhoclcgbbxoqste) about GND redirect added by the tool. I think that it's better than before, but sometimes, the tool seems to [put it in again](https://www.wikidata.org/w/index.php?title=Q6144995&diff=prev&oldid=2127955820&diffmode=source).

**Comment by SimonVilleneuvewp** [comment]
I am now qualifying the elements involved with P2241 -> Q45403344 (example : https://www.wikidata.org/wiki/Q56318471#Q56318471$CFB1D2AE-6CA7-4A64-A775-6736E1977D51 )

**Comment by magnusmanske** [comment]
This should be fixed now
