### ISSUE TITLE
P973

### ISSUE THREAD

**Issue by SimonVilleneuvewp** [magnusmanske/auth2wd#6]
Hi,

The tool add link to dbpedia and frdbpedia in P973 (see https://www.wikidata.org/wiki/Q1924847#Q1924847$A29F17AD-2BE8-43AF-9C4B-C62E557F8101 and https://www.wikidata.org/wiki/Q1924847#Q1924847$EEBC5A94-F638-4329-B59E-FC0D0A309DA1). 

It didn't disturb me before, but thinking again about it, the two sites seems to me like two interwikilinks. So maybe it should insert only the dbpedia link (and no specific language version as frdbpedia) ?

The tool also add wikipedia links in this property (see https://www.wikidata.org/wiki/Q41675147#Q41675147$03973AEC-2DB1-492E-A75E-51A321794998 ). I think it shouldn't.

**Comment by magnusmanske** [comment]
I can't reproduce the frdbpedia issue (no testing example left?).

Now preventing Wikipedia links to be added as P973.

**Comment by SimonVilleneuvewp** [comment]
Epidosis seems to think that none of the DPpedia links are justified : https://quickstatements.toolforge.org/#/batch/234440
